### PR TITLE
Enable connection pooling and gzip

### PR DESCRIPTION
**Pull request by myagley**

### CODE REVIEW

**Comment by plainlystated** [comment]
where you able to test that this will periodically cycle the connection (so we can deploy)? Do you know if it's based on number of requests, or wall time? I was looking at the docs (http://docs.python-requests.org/en/latest/user/advanced and http://docs.python-requests.org/en/latest/api/#configurations) but didn't see mention of it.

**Comment by myagley** [comment]
I can see the connection eventually close if it's idle for a while. But, I don't know how to configure this time directly.

**Comment by plainlystated** [comment]
hmm..  ok. worse case, I guess we can just close the connection and hope the pool recovers

**Comment by myagley** [comment]
looking through the urllib3 code that handles the pool, it looks like it properly handles the connection being closed by the server. this seems like it should be configurable on the server because if it was only configurable in the clients, a malicious client could hold a connection forever

**Pull request merged**
